version: '3.9'

services:
  db:
    image: postgres:16.2-alpine
    container_name: pv-postgres162
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DATASOURCE_USER}
      - POSTGRES_PASSWORD=${DATASOURCE_PASSWORD}
    ports:
      - '5432:5432'
    volumes:
      - pv-postgres:/var/lib/postgresql/data

  places-visiting-api:
    container_name: pv-api
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    ports:
      - "8080:8080"
    environment:
      - DATASOURCE_URL=${DATASOURCE_URL}${DATABASE_NAME}
      - DATASOURCE_USER=${DATASOURCE_USER}
      - DATASOURCE_PASSWORD=${DATASOURCE_PASSWORD}
      - SPRING_SECURITY_USER_PASSWORD=${SPRING_SECURITY_USER_PASSWORD_DEFAULT}
    depends_on:
      - db

volumes:
  pv-postgres: