# Spring Boot Actuator settings
server:
  servlet:
    context-path: /api
management:
  endpoints:
    web:
      exposure:
        include: info,health
spring:
  application:
    name: trip-service-api
  datasource:
    url: ${DATASOURCE_URL:jdbc:postgresql:///trip_storage}
    username: ${DATASOURCE_USER:user}
    password: ${DATASOURCE_PASSWORD:password}
  main:
    banner-mode: off
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  security:
    oauth2:
      client:
        registration:
          google:
            client-name: Google
            client-id: ${GOOGLE_OAUTH_CLIENT_ID}
            client-secret: ${GOOGLE_OAUTH_CLIENT_SECRET}
            scope:
              - profile
              - email
              - address
              - phone
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USERNAME:someuser}
    password: ${RABBIT_PASSWORD:random_password}

logging:
  level:
    root: INFO
jwt:
  shared-key: ${JWT_SHARED_KEY:DEFAULT64CHARKEY5368566D5970337336763979244226452948404D63510000}
auth-internal-client:
  url: ${AUTH_INTERNAL_URL}
  token: ${AUTH_INTERNAL_TOKEN}

queue:
  outbound:
    notification: notification-queue
    email-calendar-event: email-calendar-event-queue
    trip-reminder: trip-reminder-queue