spring:
  mail:
    host: smtp.gmail.com
    port: 587
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enabled: true
        debug: false

    username: OVERRIDE_VALUE
    password: OVERRIDE_VALUE