@HOST=http://127.0.0.1:8080/api
@account="user"
###

###
# @name Test unauthenticated
GET {{HOST}}/test

> {%
  client.test("Unauthorized request", function () {
    client.assert(response.status === 401, "Response status is not 401");
  });
%}


###
# @name Test authenticated
GET {{HOST}}/test
Authorization: Bearer {{auth-bearer-token}}

> {%
  client.test("Authorized request", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Received expected response", function () {
    client.assert(response.body === 'You are authenticated', "Unexpected response body");
  });
%}


###
# @name Get current principal info
GET {{HOST}}/principal
Authorization: Bearer {{auth-bearer-token}}

> {%
  client.test("Authorized request", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Received expected response", function () {
    client.assert(response.body, "Unexpected response body");
    const sourceKeys = Object.keys(response.body);
    client.assert(
      sourceKeys.includes("password") && sourceKeys.includes("username"),
      "Not enough of fields");
  });
%}

###
# @name Attempt to get principal info but not authenticated (should be no session data)
#@no-redirect
GET {{HOST}}/principal

> {%
  client.test("Unauthorized request", function () {
    client.assert(response.status === 401, "Response status is not 401");
  });
%}

###
# @name Create place without authentication. No need to have body
POST {{HOST}}/places

> {%
  client.test("Unauthorized request", function () {
    client.assert(response.status === 401, "Response status is not 401");
  });
%}

###
# @name Login with existing user to manipulate with places
POST {{HOST}}/account/login
Content-Type: application/json

{
  "username": "user",
  "password": "pass"
}

> {%
  client.global.set("auth-bearer-token", null);
  client.test("User login successfully", function () {
    client.assert(response.status === 200, "Response status is not 200");
    const token = response.body;
    client.global.set("auth-bearer-token", token);
  });
%}

###
# @name Create place.
POST {{HOST}}/places
Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}

{
  "name": "PlaceName",
  "country": "Poland",
  "address": "rondo ONZ"
}

> {%
  client.test("Place created", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Received expected response", function () {
    client.assert(response.body, "Unexpected response body");
    const sourceKeys = Object.keys(response.body);
    client.assert(
      sourceKeys.includes("id") && sourceKeys.includes("name"),
      "Not enough of fields");
  });
%}

###
# @name Get existing place
GET {{HOST}}/places/1
#Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}

> {%
  client.test("Place exists", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Received expected response", function () {
    client.assert(response.body, "Unexpected response body");
    const sourceKeys = Object.keys(response.body);
    client.assert(
      sourceKeys.includes("id") && sourceKeys.includes("name"),
      "Not enough of fields");
  });
%}

###
# @name Get unexisting place
GET {{HOST}}/places/1000
#Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}

> {%
  client.test("PLace doesn't exists", function () {
    client.assert(response.status === 404, "Response status is not 404");
  });
%}

###
# @name Rename of unexisting place
PATCH {{HOST}}/places/1000
Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}

{
  "name": "Any"
}

> {%
  client.test("PLace doesn't exists", function () {
    client.assert(response.status === 404, "Response status is not 404");
  });
%}

###
# @name Place rename
PATCH {{HOST}}/places/1
Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}

{
  "name": "Roundabout ONZ in Warsaw"
}

> {%
  client.test("Place updated", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Received expected response", function () {
    client.assert(response.body, "Unexpected response body");
    client.assert(response.body.name === "Roundabout ONZ in Warsaw", "Name was updated");
  });
%}

###
# @name Add position to place
PATCH {{HOST}}/places/1
Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}

{
  "latitude": 52.233215,
  "longitude": 20.998458
}

> {%
  client.test("Place updated", function () {
    client.assert(response.status === 200, "Response status is not 200");
  });
  client.test("Received expected response", function () {
    client.assert(response.body, "Unexpected response body");
    client.assert(response.body.latitude === 52.233215, "Latitude was updated");
    client.assert(response.body.longitude === 20.998458, "Longitude was updated");
  });
%}

###
# @name Create trip
POST {{HOST}}/trips
Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}

{
  "date": "01/02/2025",
  "placeId": 1,
  "companions": ["mike@gmail.com"]
}

###
# @name Create another trip
POST {{HOST}}/trips
Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}

{
  "date": "01/12/2024",
  "placeId": 2
}

###
# @name Create new trip with new place
POST {{HOST}}/trips
Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}

{
  "date": "01/12/2024",
  "place": {
    "name": "rondo Daszyńskiego",
    "country": "Poland",
    "address": "rondo Daszyńskiego"
  }
}

###
# @name Test notification message
POST {{HOST}}/message
Content-Type: application/json
Authorization: Bearer {{auth-bearer-token}}
