spring:
  main:
    banner-mode: off
  application:
    name: email-service
  rabbitmq:
    host: ${RABBIT_HOST:localhost}
    username: ${RABBIT_USERNAME:someuser}
    password: ${RABBIT_PASSWORD:random_password}
  mail:
    username: ${GMAIL_USER_NAME:OVERRIDE_VALUE}
    password: ${GMAIL_TOKEN:OVERRIDE_VALUE}

logging:
  level:
    info.mastera.emailservice.listener: DEBUG

queue:
  inbound:
    email-calendar-event: email-calendar-event-queue
    trip-reminder: trip-reminder-queue

auth-internal-client:
  url: ${AUTH_INTERNAL_URL}
  token: ${AUTH_INTERNAL_TOKEN}